### ISSUE TITLE
Demo App Storyboard

### ISSUE THREAD

**Issue by barlock** [ConsenSys/web3studio-bootleg#115] opened 2019-02-18 14:21 UTC
@breakpointer commented on [Wed Feb 13 2019](https://github.com/ConsenSys/web3studio-soy/issues/61)

## Overview

As a developer so I know how to build the demo app, I want to review a story board to understand the requirements and how the app will be used.

### Reference

- Existing epic tickets

### Questions

- What is needed for SxSW and what is not

### Assumptions

- Can be done with wireframe drawings

### Acceptance

- A set of screens that shows the app logic and illustrates the users interaction

**Comment by breakpointer** [comment] 2019-04-04 13:57
Duplicate of #159

**Closed by breakpointer** 2019-04-04 13:57 UTC
